---
name: ci

"on":
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    paths-ignore:
      - "**/*.md"
  schedule:
    - cron: 0 2 * * 0

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linting tools
        run: brew install shellcheck yamllint markdownlint-cli2

      - name: yamllint
        run: yamllint .

      - name: markdownlint-cli2
        run: markdownlint-cli2 "**/*.md"

      - name: shellcheck
        run: |
          find . -maxdepth 1 -type f \
            ! -name "*.sh" \
            ! -name "*.bash" \
            ! -name "*.zsh" \
            -exec sh -c '
              for file; do
                head -n1 "$file" | grep -qE "^#!.*(sh|bash|zsh)" && echo "$file"
              done
            ' sh {} + \
          | xargs shellcheck
