---
name: ci

"on":
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    paths-ignore:
      - "**/*.md"
  schedule:
    - cron: 0 2 * * 0

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: dotfiles

      - name: Install linting tools
        run: brew install shellcheck yamllint markdownlint-cli2 zsh

      - name: yamllint
        run: yamllint .

      - name: markdownlint-cli2
        run: markdownlint-cli2 "**/*.md"

      - name: shellcheck
        run: |
          files=$(find . -type f ! -path './.git/*' -exec sh -c '
            for file; do
              head -n 1 "$file" \
              | grep -Eq "^#!(/usr/bin/env )?(bash|sh)$" && echo "$file"
            done
          ' sh {} +)

          if [ -n "$files" ]; then
            echo "$files"
            echo "$files" | xargs shellcheck
            if [ $? -eq 0 ]; then
              echo "No errors found in bash or shell script files."
              exit 0
            fi
          else
            echo "No matching shell scripts found to check."
            exit 0
          fi

      - name: zsh
        run: |
          files=$(find . -type f \( -name 'zshrc' -o -name '*.zsh' \))

          if [ -n "$files" ]; then
            echo "$files"
            echo "$files" | xargs zsh -n
            if [ $? -eq 0 ]; then
              echo "No errors found in zsh files."
              exit 0
            fi
          else
            echo "No matching zsh scripts found to check."
              exit 0
          fi
  test:
    needs: lint
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: dotfiles

      - name: Install test tools
        run: brew install rcm

      - name: Install dotfiles
        run: env RCRC=$GITHUB_WORKSPACE/dotfiles/rcrc rcup
